inherit_from: .rubocop_todo.yml

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - "db/**/*"

#turn off end of line checks, git will fix this
EndOfLine:
  Enabled: false

# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Exclude:
    - "db/schema.rb"

Metrics/ClassLength:
  Exclude:
    - "test/models/user_test.rb"
