class ComplexUserSerializer < ActiveModel::Serializer
  attributes  :email,
              :zip,
              :mentor,
              :first_name,
              :last_name,
              :bio,
              :verified,
              :state,
              :address1,
              :address2,
              :city,
              :username,
              :volunteer,
              :branch_of_service,
              :years_of_service,
              :pay_grade,
              :military_occupational_specialty,
              :github,
              :twitter,
              :linked_in,
              :employment_status,
              :education,
              :military_status,
              :company_role,
              :company_name,
              :education_level,
              :scholarship_info,
              interests: []
end
