# Operation Code Team Member Listing
# Each entry should contain the following:
#- name: <Team Member Name>
#  role: <Team Member Role>
#
# Each entry must start on a new line with - name:

- name: Amy Tan
  role: CFO
  email: amy@operationcode.org

- name: Ashley Templet
  role: CCO
  email: ashley@operationcode.org

- name: David Reis
  role: COO acting

- name: Jameel Matin
  role: Public Policy Director
  email: jameel@operationcode.org

- name: Jennifer Weidman
  role: CCMO CDO
  email: jennifer@operationcode.org

- name: Kelly MacLeod
  role: People Operations
  email: kelly@operationcode.org

- name: Matthew Walter
  role: Infrastructure Lead

- name: Harry Levine
  role: Backend Lead

- name: Kyle Holmberg
  role: Frontend Lead

- name: Maggie Molina
  role: Code Schools

- name: Nell Shamrell
  role: CTO
  email: nell@operationcode.org

- name: Stephano D'Aniello
  role: General Counsel
